"""JSON serializer — writes pipeline output to the data/ directory."""
import json
import os
from datetime import datetime, timezone, timedelta


class Serializer:
    def __init__(self, data_dir: str = "data"):
        self.data_dir = data_dir
        self.beijing_tz = timezone(timedelta(hours=8))

    def serialize(self, articles: list, daily_en: str, daily_zh: str) -> str:
        """Serialize articles and digest to JSON files. Returns the date string."""
        print("[Pipeline] Stage 5: Serializing output...")

        now = datetime.now(tz=self.beijing_tz)
        date_str = now.strftime("%Y-%m-%d")
        date_dir = os.path.join(self.data_dir, date_str)
        os.makedirs(date_dir, exist_ok=True)

        articles_data = {
            "date": date_str,
            "generated_at": now.isoformat(),
            "total_articles": len(articles),
            "daily_observation_en": daily_en,
            "daily_observation_zh": daily_zh,
            "articles": [a.to_dict() for a in articles],
        }

        articles_path = os.path.join(date_dir, "articles.json")
        with open(articles_path, "w", encoding="utf-8") as f:
            json.dump(articles_data, f, ensure_ascii=False, indent=2)

        brief_en = self._generate_markdown(articles, daily_en, "en")
        brief_zh = self._generate_markdown(articles, daily_zh, "zh")

        with open(os.path.join(date_dir, "brief_en.md"), "w", encoding="utf-8") as f:
            f.write(brief_en)
        with open(os.path.join(date_dir, "brief_zh.md"), "w", encoding="utf-8") as f:
            f.write(brief_zh)

        self._update_index(date_str, articles_data)
        self._update_search_index(date_str, articles)

        print(f"  Output written to {date_dir}/")
        print(f"  - articles.json ({len(articles)} articles)")
        print(f"  - brief_en.md, brief_zh.md")
        return date_str

    def _generate_markdown(self, articles: list, daily_observation: str, lang: str) -> str:
        """Generate human-readable Markdown digest."""
        lang_label = "English" if lang == "en" else "中文"

        lines = [
            f"# 🤖 AI News Daily Digest — {lang_label}",
            "",
            f"> {daily_observation}" if daily_observation else "",
            "",
            "---",
            "",
        ]

        categories = {}
        for a in articles:
            cat = a.category or "industry"
            if cat not in categories:
                categories[cat] = []
            categories[cat].append(a)

        cat_emoji = {
            "research": "🔬",
            "industry": "🏭",
            "tools": "🛠️",
            "opinion": "💭",
        }

        for cat, cat_articles in categories.items():
            emoji = cat_emoji.get(cat, "📌")
            lines.append(f"## {emoji} {cat.upper()}")
            lines.append("")
            for a in cat_articles:
                title = a.title_en if lang == "en" else a.title_zh
                summary = a.summary_en if lang == "en" else a.summary_zh
                title = title or a.title
                lines.append(f"### [{a.score:.1f}] {title}")
                lines.append(f"📡 {a.source_name} · {a.source_type}")
                lines.append("")
                if summary:
                    lines.append(summary)
                    lines.append("")
                lines.append(f"🔗 [{a.url}]({a.url})")
                lines.append("")
                if a.key_points_en and lang == "en":
                    for kp in a.key_points_en[:2]:
                        lines.append(f"- {kp}")
                    lines.append("")
                elif a.key_points_zh and lang == "zh":
                    for kp in a.key_points_zh[:2]:
                        lines.append(f"- {kp}")
                    lines.append("")
                lines.append("---")
                lines.append("")

        lines.extend([
            "",
            "---",
            f"*Generated by AI Pulse on {datetime.now().strftime('%Y-%m-%d %H:%M')} Beijing Time*",
        ])

        return "\n".join(lines)

    def _update_index(self, date_str: str, articles_data: dict):
        """Update the index.json registry of all daily digests."""
        index_path = os.path.join(self.data_dir, "index.json")
        index = {}
        if os.path.exists(index_path):
            with open(index_path, "r", encoding="utf-8") as f:
                index = json.load(f)

        index[date_str] = {
            "date": date_str,
            "total_articles": articles_data["total_articles"],
            "categories": {},
        }
        for a in articles_data["articles"]:
            cat = a.get("category", "industry")
            index[date_str]["categories"][cat] = index[date_str]["categories"].get(cat, 0) + 1

        with open(index_path, "w", encoding="utf-8") as f:
            json.dump(index, f, ensure_ascii=False, indent=2)

    def _update_search_index(self, date_str: str, articles: list):
        """Update the full-text search index."""
        idx_path = os.path.join(self.data_dir, "search-index.json")
        search_entries = []
        if os.path.exists(idx_path):
            with open(idx_path, "r", encoding="utf-8") as f:
                search_entries = json.load(f)

        for a in articles:
            text = f"{a.title} {a.title_en} {a.title_zh} {a.summary_en} {a.summary_zh} {a.source_name}"
            search_entries.append({
                "id": a.id,
                "date": date_str,
                "title_en": a.title_en or a.title,
                "title_zh": a.title_zh or a.title,
                "source_type": a.source_type,
                "source_name": a.source_name,
                "category": a.category,
                "score": a.score,
                "url": a.url,
                "text": text,
            })

        with open(idx_path, "w", encoding="utf-8") as f:
            json.dump(search_entries, f, ensure_ascii=False, indent=2)
